export enum Permission {
  // Organization
  ORG_MANAGE_SETTINGS = 'ORG_MANAGE_SETTINGS',
  ORG_INVITE_MEMBERS = 'ORG_INVITE_MEMBERS',
  ORG_REMOVE_MEMBERS = 'ORG_REMOVE_MEMBERS',
  ORG_DELETE = 'ORG_DELETE',

  // Workspace
  WORKSPACE_CREATE_PROJECT = 'WORKSPACE_CREATE_PROJECT',
  WORKSPACE_EDIT_SETTINGS = 'WORKSPACE_EDIT_SETTINGS',
  WORKSPACE_MANAGE_MEMBERS = 'WORKSPACE_MANAGE_MEMBERS',

  // Project
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_EDIT = 'PROJECT_EDIT',
  PROJECT_DELETE = 'PROJECT_DELETE',

  // Task
  TASK_CREATE = 'TASK_CREATE',
  TASK_EDIT = 'TASK_EDIT',
  TASK_DELETE = 'TASK_DELETE',
  TASK_ASSIGN = 'TASK_ASSIGN',
  TASK_CHANGE_STATUS = 'TASK_CHANGE_STATUS',

  // Comment
  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_DELETE = 'COMMENT_DELETE',

  // File
  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DELETE = 'FILE_DELETE',
}

export enum RoleName {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  GUEST = 'GUEST',
}
